import datetime
from http import HTTPStatus
from sqlalchemy import and_,func
from flask_jwt_extended import jwt_required
from flask_restplus import Resource, reqparse, fields
from ...settings import sess #(.) itu nunjukkin mundur satu langkah
from ..api import api
from ...database import Pasien,TesLab,CheckIn

checkinpasienbaru_namespace = api.namespace('v1/checkin_pasien_baru', description='New patient + checkin') #

_data_get_req = reqparse.RequestParser()
_data_get_req.add_argument('nama', required=True, location='form', help='Your Full Name')
_data_get_req.add_argument('noKTP', required=True, location='form',   help='no KTP (16 digit)')
_data_get_req.add_argument('tanggalLahir', required=True, location='form', help='YYYY/MM/DD')
_data_get_req.add_argument('jenisKelamin', location='form', choices=('L','P'),help='Gender (L/P)')
_data_get_req.add_argument('alamat', required=True, location='form', help='Address')
_data_get_req.add_argument('notelp', required=True, location='form', help='Phone number')
_data_get_req.add_argument('Statusregistrasi', required=True, location='form', choices=('Rujukan','Umum'), help='Rujukan/Umum')
_data_get_req.add_argument('metodebayar', required=True, location='form', choices=('Asuransi','Umum'), help='YYYY/MM/DD')
_data_get_req.add_argument('statusbayar', default='Belum Bayar',location='form', choices=('Sudah Bayar','Belum Bayar'),help='Sudah Bayar/Belum Bayar')
_data_get_req.add_argument('UjiLab',action='split', required=True, location='form',help='Uji lab apa saja yang akan ditambahkan')


_data_get_return = api.model('Token', {
    'status':fields.String(description='Status Berhasil'),
   # 'token' : fields.String(description='Generated token to use for requesting REST APIs') #bisa tambahin status nanti
})

@checkinpasienbaru_namespace.route('')
@api.doc(responses={
    HTTPStatus.UNPROCESSABLE_ENTITY:'Invalid token.'
})
class pasienAPI(Resource):
    @jwt_required
    @api.expect(_data_get_req, validate=True)
    @api.response(HTTPStatus.UNAUTHORIZED, 'gagal masuk')
    @api.marshal_with(_data_get_return, description='Token generated.')
    def post(self):
        r = _data_get_req.parse_args()
        result = {'status': None}
        nama = r['nama']
        noKTP = r['noKTP']
        tanggalLahir = r['tanggalLahir']
        jenisKelamin = r['jenisKelamin']
        alamat   = r['alamat']
        notelp = r['notelp']
        Statusregistrasi = r['Statusregistrasi']
        metodebayar = r['metodebayar']
        statusbayar = r['statusbayar']
        ujilab = r['UjiLab']
        waktu = datetime.datetime.now()
        shift = datetime.datetime.now().strftime("%X")
        # buat jadwal shift perawat
        if ((shift > "06:59:00") and (shift < "12:00:00")):
            perawatID = 2  # ini contoh kasus, nanti bisa diganti
        elif ((shift > "11:59:59") and (shift < "17:00:00")):
            perawatID = 3
        elif ((shift > "16:59:59") and (shift < "22:00:00")):
            perawatID = 4

        session = sess()
        query   = session.query(Pasien).filter(and_(Pasien.nama == nama,
                                                   Pasien.noKTP==noKTP,
                                                   Pasien.tglLahir==tanggalLahir,
                                                   Pasien.jenisKelamin== jenisKelamin,
                                                   )).one_or_none()
        if query:
            result['status'] = 'Sudah terdaftar'
        else:
            entry               = Pasien(nama,noKTP,notelp,tanggalLahir,jenisKelamin,alamat)
            session.add(entry)
            result['status']    = 'Akun Pasien berhasil dibuat'
            session.commit()

            entry_checkin = CheckIn(noKTP, Statusregistrasi, metodebayar, statusbayar,
                            waktu)  # waktu itu waktu masuknya data dari frontend, jadi autogenerated
            session.add(entry_checkin)
            session.commit()
            no = session.query(func.max(CheckIn.id))  # no checkIn yang terakhir
            for i in range(len(ujilab)):
                lab = TesLab(no, perawatID, ujilab[i], None, None, None, waktu, None)
                session.add(lab)
                session.commit()
            # sekarang buat masukin data di lab
            result['status'] = 'Check-in berhasil'
            session.close()
        return result