"""versi3

Revision ID: c42d72b6832a
Revises: 
Create Date: 2020-01-13 15:15:16.663281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c42d72b6832a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('nama', sa.String(), nullable=True),
    sa.Column('jabatan', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('dokter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dokter_id', sa.String(), nullable=True),
    sa.Column('nama', sa.String(), nullable=True),
    sa.Column('statusPegawai', sa.String(), nullable=True),
    sa.Column('notelp', sa.Integer(), nullable=True),
    sa.Column('alamat', sa.String(), nullable=True),
    sa.Column('spesialis', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dokter_dokter_id'), 'dokter', ['dokter_id'], unique=True)
    op.create_index(op.f('ix_dokter_nama'), 'dokter', ['nama'], unique=False)
    op.create_index(op.f('ix_dokter_notelp'), 'dokter', ['notelp'], unique=False)
    op.create_table('lab',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.String(), nullable=True),
    sa.Column('kepalaLab', sa.String(), nullable=True),
    sa.Column('alatTes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_nama'), 'lab', ['nama'], unique=False)
    op.create_table('pasien',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.String(), nullable=True),
    sa.Column('noKTP', sa.String(), nullable=True),
    sa.Column('tglLahir', sa.Date(), nullable=True),
    sa.Column('jenisKelamin', sa.String(), nullable=True),
    sa.Column('alamat', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pasien_alamat'), 'pasien', ['alamat'], unique=False)
    op.create_index(op.f('ix_pasien_nama'), 'pasien', ['nama'], unique=False)
    op.create_index(op.f('ix_pasien_noKTP'), 'pasien', ['noKTP'], unique=True)
    op.create_table('alat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=True),
    sa.Column('nama', sa.String(), nullable=True),
    sa.Column('harga', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], ['lab.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alat_lab_id'), 'alat', ['lab_id'], unique=False)
    op.create_index(op.f('ix_alat_nama'), 'alat', ['nama'], unique=True)
    op.create_table('check_in',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('PasienID', sa.String(), nullable=True),
    sa.Column('Statusregistrasi', sa.String(), nullable=True),
    sa.Column('metodebayar', sa.String(), nullable=True),
    sa.Column('statusbayar', sa.String(), nullable=True),
    sa.Column('waktuMulai', sa.DateTime(), nullable=True),
    sa.Column('waktuSelesai', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['PasienID'], ['pasien.noKTP'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_in_PasienID'), 'check_in', ['PasienID'], unique=False)
    op.create_table('perawat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=True),
    sa.Column('nama', sa.String(), nullable=True),
    sa.Column('statusPegawai', sa.String(), nullable=True),
    sa.Column('notelp', sa.Integer(), nullable=True),
    sa.Column('alamat', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], ['lab.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perawat_lab_id'), 'perawat', ['lab_id'], unique=False)
    op.create_index(op.f('ix_perawat_nama'), 'perawat', ['nama'], unique=False)
    op.create_table('tesLab',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CheckInID', sa.Integer(), nullable=True),
    sa.Column('PerawatID', sa.Integer(), nullable=True),
    sa.Column('alatID', sa.String(), nullable=True),
    sa.Column('dokterPJ', sa.String(), nullable=True),
    sa.Column('noUrut', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('statusVerif', sa.String(), nullable=True),
    sa.Column('hasil', sa.TEXT(), nullable=True),
    sa.Column('waktuMulai', sa.DateTime(), nullable=True),
    sa.Column('waktuSelesai', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['CheckInID'], ['check_in.id'], ),
    sa.ForeignKeyConstraint(['PerawatID'], ['perawat.id'], ),
    sa.ForeignKeyConstraint(['alatID'], ['alat.nama'], ),
    sa.ForeignKeyConstraint(['dokterPJ'], ['dokter.dokter_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tesLab_CheckInID'), 'tesLab', ['CheckInID'], unique=False)
    op.create_table('dokterLab',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teslabID', sa.Integer(), nullable=True),
    sa.Column('dokterID', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dokterID'], ['dokter.dokter_id'], ),
    sa.ForeignKeyConstraint(['teslabID'], ['tesLab.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dokterLab')
    op.drop_index(op.f('ix_tesLab_CheckInID'), table_name='tesLab')
    op.drop_table('tesLab')
    op.drop_index(op.f('ix_perawat_nama'), table_name='perawat')
    op.drop_index(op.f('ix_perawat_lab_id'), table_name='perawat')
    op.drop_table('perawat')
    op.drop_index(op.f('ix_check_in_PasienID'), table_name='check_in')
    op.drop_table('check_in')
    op.drop_index(op.f('ix_alat_nama'), table_name='alat')
    op.drop_index(op.f('ix_alat_lab_id'), table_name='alat')
    op.drop_table('alat')
    op.drop_index(op.f('ix_pasien_noKTP'), table_name='pasien')
    op.drop_index(op.f('ix_pasien_nama'), table_name='pasien')
    op.drop_index(op.f('ix_pasien_alamat'), table_name='pasien')
    op.drop_table('pasien')
    op.drop_index(op.f('ix_lab_nama'), table_name='lab')
    op.drop_table('lab')
    op.drop_index(op.f('ix_dokter_notelp'), table_name='dokter')
    op.drop_index(op.f('ix_dokter_nama'), table_name='dokter')
    op.drop_index(op.f('ix_dokter_dokter_id'), table_name='dokter')
    op.drop_table('dokter')
    op.drop_table('app_user')
    # ### end Alembic commands ###
